name: Clawdex
options:
  bundleIdPrefix: se.advatar
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    DEVELOPMENT_TEAM: JS498PMF4Z
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
targets:
  Clawdex:
    type: application
    platform: macOS
    sources:
      - path: Sources/Clawdex
    resources:
      - path: Resources
    entitlements:
      path: Resources/Clawdex.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: se.advatar.Clawdex
        CODE_SIGN_ENTITLEMENTS: Resources/Clawdex.entitlements
        GENERATE_INFOPLIST_FILE: YES
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        SWIFT_VERSION: "6.2"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Advatar Systems AB"
    postBuildScripts:
      - name: Build and embed Rust tools (codex + clawdex)
        script: Scripts/build_and_embed_rust.sh
        basedOnDependencyAnalysis: false
