name: ClawdApp
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    DEVELOPMENT_TEAM: YOURTEAMID
targets:
  ClawdApp:
    type: application
    platform: macOS
    sources:
      - path: Sources/ClawdApp
    resources:
      - path: Resources
    entitlements:
      path: Resources/ClawdApp.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.ClawdApp
        CODE_SIGN_ENTITLEMENTS: Resources/ClawdApp.entitlements
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Your Company"
    postBuildScripts:
      - name: Build and embed Rust tools (codex + codex-clawd)
        script: Scripts/build_and_embed_rust.sh
        basedOnDependencyAnalysis: false
